services:
  catalogue: 
    build:
      context: ./catalogue
      dockerfile: Dockerfile 
    image: Meghanai/catalogue:1.0.0 
    container_name: catalogue
    depends_on:
      - mongodb

  mongodb:
    build: 
      context: ./mongodb
      dockerfile: Dockerfile
    image: Meghanai/mongodb:1.0.0
    container_name: mongodb

networks:
  default:
    driver: bridge
    name: roboshop
    external: false